version: 0.2

phases:
  install:
    commands:
      - choco install -y maven
      - choco install -y googlechrome
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn allure:report
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/site/allure-maven-plugin/**/*
    - appspec.yml
cache:
  paths:
    - 'C:/Users/ContainerAdministrator/AppData/Local/Temp/chocolatey/**/*'
    - 'C:/Users/ContainerAdministrator/.m2/**/*'